server:
  # UTF-8
  servlet:
    encoding:
      charset: UTF-8
  port: ${port:8080}
  ssl:
    key-store: 경로
    key-store-password: 비밀번호
    key-alias: tomcat
    key-store-type: PKCS12
    enabled: true
# thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


