server:
  # UTF-8
  servlet:
    encoding:
      charset: UTF-8
  port: ${port:8080}

# thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.joebrooks.mapshotserver.domain.map.kakao: DEBUG

